//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;
using System;

[assembly: AssemblyTitle("Cake.Openshift")]
[assembly: AssemblyDescription("Cake Openshift AddIn")]
[assembly: AssemblyCompany("Cake Contributions")]
[assembly: AssemblyProduct("Cake.Openshift")]
[assembly: AssemblyVersion("0.4.0")]
[assembly: AssemblyFileVersion("0.4.0")]
[assembly: AssemblyInformationalVersion("0.4.0")]
[assembly: AssemblyCopyright("Copyright © Cake Contributions 2017 - Present")]
[assembly: CLSCompliant(true)]